sudo: false
language: go
go:
- 1.8
- tip

cache:
  directories:
  - $GOPATH/src
  - $GOPATH/pkg

before_install:
- go get golang.org/x/tools/cmd/cover
- go get -u github.com/golang/dep/...

install:
- dep status

script:
- go test -i
- go test -race
- go test -coverprofile=coverage.out
- go tool cover -func=coverage.out
- go build ./example/main.go
