
[[dependencies]]
  branch = "master"
  name = "github.com/spf13/pflag"

[[dependencies]]
  branch = "master"
  name = "golang.org/x/crypto"

[[dependencies]]
  name = "k8s.io/client-go"
  version = "v2.0.0"
