steps:
  - command: go build ./... && go test ./...
    plugins:
      - golang#v2.0.0:
          version: "1.12"
          import: github.com/micahhausler/k8s-acme-cache
          environment:
            - GO111MODULE=on
